// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run optimize:images` to regenerate.
import type { StaticImageData } from "next/image";

import full0 from "../assets/optimized/best-talks/best-talks-01-full.webp";
import thumb0 from "../assets/optimized/best-talks/best-talks-01-thumb.webp";
import full1 from "../assets/optimized/best-talks/best-talks-02-full.webp";
import thumb1 from "../assets/optimized/best-talks/best-talks-02-thumb.webp";
import full2 from "../assets/optimized/best-talks/best-talks-03-full.webp";
import thumb2 from "../assets/optimized/best-talks/best-talks-03-thumb.webp";
import full3 from "../assets/optimized/best-talks/best-talks-04-full.webp";
import thumb3 from "../assets/optimized/best-talks/best-talks-04-thumb.webp";
import full4 from "../assets/optimized/best-talks/best-talks-05-full.webp";
import thumb4 from "../assets/optimized/best-talks/best-talks-05-thumb.webp";
import full5 from "../assets/optimized/best-talks/best-talks-06-full.webp";
import thumb5 from "../assets/optimized/best-talks/best-talks-06-thumb.webp";
import full6 from "../assets/optimized/best-talks/best-talks-07-full.webp";
import thumb6 from "../assets/optimized/best-talks/best-talks-07-thumb.webp";
import full7 from "../assets/optimized/best-talks/best-talks-08-full.webp";
import thumb7 from "../assets/optimized/best-talks/best-talks-08-thumb.webp";
import full8 from "../assets/optimized/best-talks/best-talks-09-full.webp";
import thumb8 from "../assets/optimized/best-talks/best-talks-09-thumb.webp";
import full9 from "../assets/optimized/best-talks/best-talks-10-full.webp";
import thumb9 from "../assets/optimized/best-talks/best-talks-10-thumb.webp";
import full10 from "../assets/optimized/best-talks/best-talks-11-full.webp";
import thumb10 from "../assets/optimized/best-talks/best-talks-11-thumb.webp";
import full11 from "../assets/optimized/best-talks/best-talks-12-full.webp";
import thumb11 from "../assets/optimized/best-talks/best-talks-12-thumb.webp";
import full12 from "../assets/optimized/best-talks/best-talks-13-full.webp";
import thumb12 from "../assets/optimized/best-talks/best-talks-13-thumb.webp";
import full13 from "../assets/optimized/best-talks/best-talks-14-full.webp";
import thumb13 from "../assets/optimized/best-talks/best-talks-14-thumb.webp";
import full14 from "../assets/optimized/best-talks/best-talks-15-full.webp";
import thumb14 from "../assets/optimized/best-talks/best-talks-15-thumb.webp";
import full15 from "../assets/optimized/best-talks/best-talks-16-full.webp";
import thumb15 from "../assets/optimized/best-talks/best-talks-16-thumb.webp";
import full16 from "../assets/optimized/best-talks/best-talks-17-full.webp";
import thumb16 from "../assets/optimized/best-talks/best-talks-17-thumb.webp";
import full17 from "../assets/optimized/best-talks/best-talks-18-full.webp";
import thumb17 from "../assets/optimized/best-talks/best-talks-18-thumb.webp";
import full18 from "../assets/optimized/best-talks/best-talks-19-full.webp";
import thumb18 from "../assets/optimized/best-talks/best-talks-19-thumb.webp";
import full19 from "../assets/optimized/best-talks/best-talks-20-full.webp";
import thumb19 from "../assets/optimized/best-talks/best-talks-20-thumb.webp";
import full20 from "../assets/optimized/best-talks/best-talks-21-full.webp";
import thumb20 from "../assets/optimized/best-talks/best-talks-21-thumb.webp";
import full21 from "../assets/optimized/best-talks/best-talks-22-full.webp";
import thumb21 from "../assets/optimized/best-talks/best-talks-22-thumb.webp";
import full22 from "../assets/optimized/recrutari/recrutari-01-full.webp";
import thumb22 from "../assets/optimized/recrutari/recrutari-01-thumb.webp";
import full23 from "../assets/optimized/recrutari/recrutari-02-full.webp";
import thumb23 from "../assets/optimized/recrutari/recrutari-02-thumb.webp";
import full24 from "../assets/optimized/recrutari/recrutari-03-full.webp";
import thumb24 from "../assets/optimized/recrutari/recrutari-03-thumb.webp";
import full25 from "../assets/optimized/recrutari/recrutari-04-full.webp";
import thumb25 from "../assets/optimized/recrutari/recrutari-04-thumb.webp";
import full26 from "../assets/optimized/recrutari/recrutari-05-full.webp";
import thumb26 from "../assets/optimized/recrutari/recrutari-05-thumb.webp";
import full27 from "../assets/optimized/recrutari/recrutari-06-full.webp";
import thumb27 from "../assets/optimized/recrutari/recrutari-06-thumb.webp";
import full28 from "../assets/optimized/recrutari/recrutari-07-full.webp";
import thumb28 from "../assets/optimized/recrutari/recrutari-07-thumb.webp";
import full29 from "../assets/optimized/recrutari/recrutari-08-full.webp";
import thumb29 from "../assets/optimized/recrutari/recrutari-08-thumb.webp";
import full30 from "../assets/optimized/recrutari/recrutari-09-full.webp";
import thumb30 from "../assets/optimized/recrutari/recrutari-09-thumb.webp";
import full31 from "../assets/optimized/recrutari/recrutari-10-full.webp";
import thumb31 from "../assets/optimized/recrutari/recrutari-10-thumb.webp";
import full32 from "../assets/optimized/recrutari/recrutari-11-full.webp";
import thumb32 from "../assets/optimized/recrutari/recrutari-11-thumb.webp";
import full33 from "../assets/optimized/recrutari/recrutari-12-full.webp";
import thumb33 from "../assets/optimized/recrutari/recrutari-12-thumb.webp";
import full34 from "../assets/optimized/recrutari/recrutari-13-full.webp";
import thumb34 from "../assets/optimized/recrutari/recrutari-13-thumb.webp";
import full35 from "../assets/optimized/recrutari/recrutari-14-full.webp";
import thumb35 from "../assets/optimized/recrutari/recrutari-14-thumb.webp";
import full36 from "../assets/optimized/recrutari/recrutari-15-full.webp";
import thumb36 from "../assets/optimized/recrutari/recrutari-15-thumb.webp";
import full37 from "../assets/optimized/recrutari/recrutari-16-full.webp";
import thumb37 from "../assets/optimized/recrutari/recrutari-16-thumb.webp";
import full38 from "../assets/optimized/recrutari/recrutari-17-full.webp";
import thumb38 from "../assets/optimized/recrutari/recrutari-17-thumb.webp";
import full39 from "../assets/optimized/recrutari/recrutari-18-full.webp";
import thumb39 from "../assets/optimized/recrutari/recrutari-18-thumb.webp";
import full40 from "../assets/optimized/recrutari/recrutari-19-full.webp";
import thumb40 from "../assets/optimized/recrutari/recrutari-19-thumb.webp";
import full41 from "../assets/optimized/recrutari/recrutari-20-full.webp";
import thumb41 from "../assets/optimized/recrutari/recrutari-20-thumb.webp";

export type EventSlug = "best-talks" | "recrutari";
export type Orientation = "landscape" | "portrait";

export type GalleryImage = {
  slug: string;
  event: EventSlug;
  label: string;
  alt: string;
  orientation: Orientation;
  full: StaticImageData;
  thumb: StaticImageData;
};

const BY_SLUG: Record<string, GalleryImage> = {
  "best-talks-01": { slug: "best-talks-01", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full0, thumb: thumb0 },
  "best-talks-02": { slug: "best-talks-02", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "portrait", full: full1, thumb: thumb1 },
  "best-talks-03": { slug: "best-talks-03", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full2, thumb: thumb2 },
  "best-talks-04": { slug: "best-talks-04", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "portrait", full: full3, thumb: thumb3 },
  "best-talks-05": { slug: "best-talks-05", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full4, thumb: thumb4 },
  "best-talks-06": { slug: "best-talks-06", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full5, thumb: thumb5 },
  "best-talks-07": { slug: "best-talks-07", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full6, thumb: thumb6 },
  "best-talks-08": { slug: "best-talks-08", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full7, thumb: thumb7 },
  "best-talks-09": { slug: "best-talks-09", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full8, thumb: thumb8 },
  "best-talks-10": { slug: "best-talks-10", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "portrait", full: full9, thumb: thumb9 },
  "best-talks-11": { slug: "best-talks-11", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full10, thumb: thumb10 },
  "best-talks-12": { slug: "best-talks-12", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full11, thumb: thumb11 },
  "best-talks-13": { slug: "best-talks-13", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full12, thumb: thumb12 },
  "best-talks-14": { slug: "best-talks-14", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full13, thumb: thumb13 },
  "best-talks-15": { slug: "best-talks-15", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full14, thumb: thumb14 },
  "best-talks-16": { slug: "best-talks-16", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full15, thumb: thumb15 },
  "best-talks-17": { slug: "best-talks-17", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full16, thumb: thumb16 },
  "best-talks-18": { slug: "best-talks-18", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full17, thumb: thumb17 },
  "best-talks-19": { slug: "best-talks-19", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full18, thumb: thumb18 },
  "best-talks-20": { slug: "best-talks-20", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full19, thumb: thumb19 },
  "best-talks-21": { slug: "best-talks-21", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full20, thumb: thumb20 },
  "best-talks-22": { slug: "best-talks-22", event: "best-talks", label: "BEST Talks", alt: "Students at a BEST Talks event in Chișinău, 2026", orientation: "landscape", full: full21, thumb: thumb21 },
  "recrutari-01": { slug: "recrutari-01", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full22, thumb: thumb22 },
  "recrutari-02": { slug: "recrutari-02", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full23, thumb: thumb23 },
  "recrutari-03": { slug: "recrutari-03", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full24, thumb: thumb24 },
  "recrutari-04": { slug: "recrutari-04", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full25, thumb: thumb25 },
  "recrutari-05": { slug: "recrutari-05", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full26, thumb: thumb26 },
  "recrutari-06": { slug: "recrutari-06", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full27, thumb: thumb27 },
  "recrutari-07": { slug: "recrutari-07", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full28, thumb: thumb28 },
  "recrutari-08": { slug: "recrutari-08", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full29, thumb: thumb29 },
  "recrutari-09": { slug: "recrutari-09", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full30, thumb: thumb30 },
  "recrutari-10": { slug: "recrutari-10", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "portrait", full: full31, thumb: thumb31 },
  "recrutari-11": { slug: "recrutari-11", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full32, thumb: thumb32 },
  "recrutari-12": { slug: "recrutari-12", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full33, thumb: thumb33 },
  "recrutari-13": { slug: "recrutari-13", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full34, thumb: thumb34 },
  "recrutari-14": { slug: "recrutari-14", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "portrait", full: full35, thumb: thumb35 },
  "recrutari-15": { slug: "recrutari-15", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full36, thumb: thumb36 },
  "recrutari-16": { slug: "recrutari-16", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full37, thumb: thumb37 },
  "recrutari-17": { slug: "recrutari-17", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "portrait", full: full38, thumb: thumb38 },
  "recrutari-18": { slug: "recrutari-18", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full39, thumb: thumb39 },
  "recrutari-19": { slug: "recrutari-19", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full40, thumb: thumb40 },
  "recrutari-20": { slug: "recrutari-20", event: "recrutari", label: "Spring Recruitment", alt: "BEST Chișinău Spring Recruitment, 2026", orientation: "landscape", full: full41, thumb: thumb41 },
};

export const IMAGES: GalleryImage[] = Object.values(BY_SLUG);
export const image = (slug: string): GalleryImage => BY_SLUG[slug] ?? IMAGES[0];

/* Deliberate role assignments — every photo a known beat. Swap slugs freely. */
export const HERO_IMAGE = image("best-talks-01");
export const CTA_IMAGE = image("recrutari-01");
export const IMPACT_IMAGE = image("best-talks-03");
export const ABOUT_IMAGE = image("best-talks-02");
export const ACTIVITY_THUMBS: GalleryImage[] = [image("best-talks-04"), image("best-talks-05"), image("best-talks-06"), image("best-talks-07"), image("best-talks-08"), image("best-talks-09")];

/* The draggable contact-sheet uses landscape-dominant frames. */
export const GALLERY: GalleryImage[] = IMAGES;
