// One-time image pipeline for BEST Chișinău.
//
//   node scripts/optimize-images.mjs   (or: npm run optimize:images)
//
// Reads the raw event photos in public/images/<event folder>/*.jpg
// (~229 MB, up to 7872 px / 15 MB each — despite ".ARW"/".CR3" in the
// names they are all JPEGs), EXIF-rotates them, and emits two right-sized
// WebP masters per photo into assets/optimized/<event-slug>/:
//
//   <slug>-full.webp   (longest edge FULL_EDGE)  — gallery / hero / feature
//   <slug>-thumb.webp  (longest edge THUMB_EDGE) — activity row thumbnails
//
// It then generates lib/gallery.ts: a typed manifest of STATIC IMPORTS so
// next/image gets dimensions + an automatic blurDataURL (the "develop"
// reveal depends on the blur placeholder). The raw folders are git-ignored
// and never shipped.

import { readdir, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC_ROOT = path.join(ROOT, "public", "images");
const OUT_ROOT = path.join(ROOT, "assets", "optimized");
const MANIFEST = path.join(ROOT, "lib", "gallery.ts");

const FULL_EDGE = 1800;
const THUMB_EDGE = 700;
const FULL_Q = 66;
const THUMB_Q = 62;

// raw folder name -> { slug, event label, alt }
const EVENTS = [
  {
    dir: "BestTalks 26",
    slug: "best-talks",
    label: "BEST Talks",
    alt: "Students at a BEST Talks event in Chișinău, 2026",
  },
  {
    dir: "Recrutari Spring 26",
    slug: "recrutari",
    label: "Spring Recruitment",
    alt: "BEST Chișinău Spring Recruitment, 2026",
  },
];

const pad = (n) => String(n).padStart(2, "0");

async function processEvent(ev) {
  const srcDir = path.join(SRC_ROOT, ev.dir);
  if (!existsSync(srcDir)) {
    console.warn(`! skipping ${ev.dir} (not found)`);
    return [];
  }
  const outDir = path.join(OUT_ROOT, ev.slug);
  await mkdir(outDir, { recursive: true });

  const files = (await readdir(srcDir))
    .filter((f) => /\.jpe?g$/i.test(f))
    .sort();

  const records = [];
  let i = 0;
  for (const file of files) {
    i += 1;
    const slug = `${ev.slug}-${pad(i)}`;
    const input = path.join(srcDir, file);

    const base = sharp(input, { failOn: "none" }).rotate(); // honor EXIF
    const meta = await base.metadata();
    const w = meta.width ?? 0;
    const h = meta.height ?? 0;
    const orientation = w >= h ? "landscape" : "portrait";

    const fullName = `${slug}-full.webp`;
    const thumbName = `${slug}-thumb.webp`;

    await base
      .clone()
      .resize({ width: w >= h ? FULL_EDGE : undefined, height: w >= h ? undefined : FULL_EDGE, withoutEnlargement: true })
      .webp({ quality: FULL_Q, effort: 5 })
      .toFile(path.join(outDir, fullName));

    await base
      .clone()
      .resize({ width: w >= h ? THUMB_EDGE : undefined, height: w >= h ? undefined : THUMB_EDGE, withoutEnlargement: true })
      .webp({ quality: THUMB_Q, effort: 5 })
      .toFile(path.join(outDir, thumbName));

    records.push({ slug, event: ev.slug, label: ev.label, alt: ev.alt, orientation, fullName, thumbName });
    process.stdout.write(`  ${slug} (${orientation}) ${w}x${h}\n`);
  }
  return records;
}

function buildManifest(records) {
  const landscape = records.filter((r) => r.orientation === "landscape");
  const portrait = records.filter((r) => r.orientation === "portrait");

  // Deterministic role assignments (swap freely — they are just slugs).
  const bestTalksLandscape = landscape.filter((r) => r.event === "best-talks");
  const recrutariLandscape = landscape.filter((r) => r.event === "recrutari");
  const heroSlug = (bestTalksLandscape[0] ?? landscape[0]).slug;
  const ctaSlug = (recrutariLandscape[0] ?? landscape[1] ?? landscape[0]).slug;
  const impactSlug = (bestTalksLandscape[1] ?? landscape[2] ?? landscape[0]).slug;
  const aboutSlug = (portrait[0] ?? landscape[0]).slug;
  const activitySlugs = records
    .filter((r) => ![heroSlug, ctaSlug, impactSlug, aboutSlug].includes(r.slug))
    .slice(0, 6)
    .map((r) => r.slug);

  const importLines = [];
  const entryLines = [];
  records.forEach((r, idx) => {
    const fv = `full${idx}`;
    const tv = `thumb${idx}`;
    importLines.push(`import ${fv} from "../assets/optimized/${r.event}/${r.fullName}";`);
    importLines.push(`import ${tv} from "../assets/optimized/${r.event}/${r.thumbName}";`);
    entryLines.push(
      `  "${r.slug}": { slug: "${r.slug}", event: "${r.event}", label: ${JSON.stringify(r.label)}, alt: ${JSON.stringify(r.alt)}, orientation: "${r.orientation}", full: ${fv}, thumb: ${tv} },`
    );
  });

  return `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run \`npm run optimize:images\` to regenerate.
import type { StaticImageData } from "next/image";

${importLines.join("\n")}

export type EventSlug = "best-talks" | "recrutari";
export type Orientation = "landscape" | "portrait";

export type GalleryImage = {
  slug: string;
  event: EventSlug;
  label: string;
  alt: string;
  orientation: Orientation;
  full: StaticImageData;
  thumb: StaticImageData;
};

const BY_SLUG: Record<string, GalleryImage> = {
${entryLines.join("\n")}
};

export const IMAGES: GalleryImage[] = Object.values(BY_SLUG);
export const image = (slug: string): GalleryImage => BY_SLUG[slug] ?? IMAGES[0];

/* Deliberate role assignments — every photo a known beat. Swap slugs freely. */
export const HERO_IMAGE = image(${JSON.stringify(heroSlug)});
export const CTA_IMAGE = image(${JSON.stringify(ctaSlug)});
export const IMPACT_IMAGE = image(${JSON.stringify(impactSlug)});
export const ABOUT_IMAGE = image(${JSON.stringify(aboutSlug)});
export const ACTIVITY_THUMBS: GalleryImage[] = [${activitySlugs
    .map((s) => `image(${JSON.stringify(s)})`)
    .join(", ")}];

/* The draggable contact-sheet uses landscape-dominant frames. */
export const GALLERY: GalleryImage[] = IMAGES;
`;
}

async function main() {
  console.log("Optimizing event photos -> WebP masters…");
  await mkdir(OUT_ROOT, { recursive: true });
  let all = [];
  for (const ev of EVENTS) {
    console.log(`\n# ${ev.dir} -> assets/optimized/${ev.slug}/`);
    const recs = await processEvent(ev);
    all = all.concat(recs);
  }
  if (all.length === 0) {
    console.error("No images processed — aborting manifest write.");
    process.exit(1);
  }
  await mkdir(path.dirname(MANIFEST), { recursive: true });
  await writeFile(MANIFEST, buildManifest(all), "utf8");
  console.log(`\n✓ ${all.length} photos -> ${all.length * 2} WebP files`);
  console.log(`✓ manifest written to lib/gallery.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
